[
    {"name": "A",
     "value": "Alpha",
 	 "russian": "<b>Ал</b>-фа",
     "morse":"· −"},
	{"name": "B",
     "value": "Bravo",
 	 "russian": "<b>Бра</b>-во",
     "morse":"− · · ·"},
	{"name": "C",
     "value": "Charlie",
 	 "russian": "<b>Чар</b>-ли",
     "morse":"− · − ·"},
	{"name": "D",
     "value": "Delta",
 	 "russian": "<b>Дел</b>-та",
     "morse":"− · ·"},
	{"name": "E",
     "value": "Echo",
 	 "russian": "<b>Э</b>-ко",
     "morse":"·"},
	{"name": "F",
     "value": "Foxtrot",
 	 "russian": "<b>Фокс</b>-трот",
     "morse":"· · - ·"},
	{"name": "G",
     "value": "Golf",
 	 "russian": "<b>Гольф</b>",
     "morse":"- - ·"},
	{"name": "H",
     "value": "Hotel",
 	 "russian": "Хо-<b>тел</b>",
     "morse":"· · · ·"},
	{"name": "I",
     "value": "India",
 	 "russian": "<b>Ин</b>-ди-а",
     "morse":"· ·"},
     {"name": "J",
     "value": "Juliet",
     "russian": "<b>Джуль</b>-этт",
     "morse":"· - - -"},
	{"name": "K",
     "value": "Kilo",
 	 "russian": "<b>Ки</b>-ло",
     "morse":"- · -"},
	{"name": "L",
     "value": "Lima",
 	 "russian": "<b>Ли</b>-ма",
     "morse":"· - · ·"},
	{"name": "M",
     "value": "Mike",
 	 "russian": "<b>Майк</b>",
     "morse":"- -"},
	{"name": "N",
     "value": "November",
 	 "russian": "Но-<b>вем</b>-бер",
     "morse":"- ·"},
    {"name": "O",
     "value": "Oscar",
     "russian": "<b>Ос</b>-кар",
     "morse":"- - -"},
    {"name": "P",
     "value": "Papa",
     "russian": "Папа",
     "morse":"· - - ·"},
    {"name": "Q",
     "value": "Quebec",
     "russian": "Кве-<b>бек</b>",
     "morse":"- - · -"},
    {"name": "R",
     "value": "Romeo",
     "russian": "<b>Ро</b>-ме-о",
     "morse":"· - ·"},
    {"name": "S",
     "value": "Sierra",
     "russian": "<b>Сьер</b>-ра",
     "morse":"· · ·"},
         {"name": "T",
     "value": "Tango",
     "russian": "<b>Тэн</b>-го",
     "morse":"-"},
         {"name": "U",
     "value": "Uniform",
     "russian": "<b>Ю</b>-ни-форм",
     "morse":"· · -"},
         {"name": "V",
     "value": "Victor",
     "russian": "<b>Вик</b>-тор",
     "morse":"· · · -"},
         {"name": "W",
     "value": "Whisky",
     "russian": "<b>Уис</b>-ски",
     "morse":"· - -"},
         {"name": "X",
     "value": "X-ray",
     "russian": "<b>Экс</b>-рэй",
     "morse":"- · · -"},
         {"name": "Y",
     "value": "Yankee",
     "russian": "<b>Ян</b>-ки",
     "morse":"- · - -"},
         {"name": "Z",
     "value": "Zulu",
     "russian": "<b>Зу</b>-лу",
     "morse":"- - · ·"},
         {"name": "1",
     "value": "One",
     "russian": "<b>Ван</b>",
     "morse": "· - - - -"},
        {"name": "2",
     "value": "Two",
     "russian": "<b>Ту</b>",
     "morse": "· · - - -"},
        {"name": "3",
     "value": "Three",
     "russian": "<b>Три</b>",
     "morse": "· · · - -"},
        {"name": "4",
     "value": "Four",
     "russian": "<b>Фо</b>-ур",
     "morse": "· · · · -"},
        {"name": "5",
     "value": "Five",
     "russian": "<b>Файф</b>",
     "morse": "· · · · ·"},
        {"name": "6",
     "value": "Six",
     "russian": "<b>Сикс</b>-лу",
     "morse": "- · · · ·"},
        {"name": "7",
     "value": "Seven",
     "russian": "<b>Се</b>-вен",
     "morse": "- - · · ·"},
        {"name": "8",
     "value": "Eight",
     "russian": "<b>Айт</b>",
     "morse": "- - - · ·"},
        {"name": "9",
     "value": "Nine",
     "russian": "<b>Най</b>-нер",
     "morse": "- - - - ·"},
        {"name": "0",
     "value": "Zero",
     "russian": "<b>Зи</b>-ро",
     "morse": "- - - - -"},
      {"name": " ",
     "value": "&nbsp;&nbsp;&nbsp;",
     "russian": "&nbsp;&nbsp;&nbsp;",
     "morse": "&nbsp;&nbsp;&nbsp;"}

  ]