[
    {"name": "A",
     "value": "<b>A</b>lpha",
 	 "russian": "<b>А</b>лфа",
     "morse":"· −"},
	{"name": "B",
     "value": "Br<b>a</b>vo",
 	 "russian": "Бр<b>а</b>во",
     "morse":"− · · ·"},
	{"name": "C",
     "value": "Ch<b>a</b>rlie",
 	 "russian": "Ч<b>а</b>рли",
     "morse":"− · − ·"},
	{"name": "D",
     "value": "D<b>e</b>lta",
 	 "russian": "Д<b>е</b>лта",
     "morse":"− · ·"},
	{"name": "E",
     "value": "<b>E</b>cho",
 	 "russian": "<b>Э</b>ко",
     "morse":"·"},
	{"name": "F",
     "value": "F<b>o</b>xtrot",
 	 "russian": "Ф<b>о</b>кстрот",
     "morse":"· · – ·"},
	{"name": "G",
     "value": "Golf",
 	 "russian": "Гольф",
     "morse":"– – ·"},
	{"name": "H",
     "value": "Hot<b>e</b>l",
 	 "russian": "Хот<b>е</b>л",
     "morse":"· · · ·"},
	{"name": "I",
     "value": "<b>I</b>ndia",
 	 "russian": "<b>И</b>ндиа",
     "morse":"· ·"},
     {"name": "J",
     "value": "J<b>u</b>liet",
     "russian": "Дж<b>у</b>льэтт",
     "morse":"· – – –"},
	{"name": "K",
     "value": "K<b>i</b>lo",
 	 "russian": "К<b>и</b>ло",
     "morse":"– · –"},
	{"name": "L",
     "value": "L<b>i</b>ma",
 	 "russian": "Л<b>и</b>ма",
     "morse":"· – · ·"},
	{"name": "M",
     "value": "Mike",
 	 "russian": "Майк",
     "morse":"– –"},
	{"name": "N",
     "value": "Nov<b>e</b>mber",
 	 "russian": "Нов<b>е</b>мбер",
     "morse":"– ·"},
    {"name": "O",
     "value": "<b>O</b>scar",
     "russian": "<b>О</b>скар",
     "morse":"– – –"},
    {"name": "P",
     "value": "Papa",
     "russian": "Папа",
     "morse":"· – – ·"},
    {"name": "Q",
     "value": "Queb<b>e</b>c",
     "russian": "Квеб<b>е</b>к",
     "morse":"– – · –"},
    {"name": "R",
     "value": "R<b>o</b>meo",
     "russian": "Р<b>о</b>мео",
     "morse":"· – ·"},
    {"name": "S",
     "value": "Si<b>e</b>rra",
     "russian": "Сь<b>е</b>рра",
     "morse":"· · ·"},
         {"name": "T",
     "value": "T<b>a</b>ngo",
     "russian": "Т<b>э</b>нго",
     "morse":"–"},
         {"name": "U",
     "value": "<b>U</b>niform",
     "russian": "<b>Ю</b>ниформ",
     "morse":"· · –"},
         {"name": "V",
     "value": "V<b>i</b>ctor",
     "russian": "В<b>и</b>ктор",
     "morse":"· · · –"},
         {"name": "W",
     "value": "Wh<b>i</b>sky",
     "russian": "У<b>и</b>сски",
     "morse":"· – –"},
         {"name": "X",
     "value": "X–ray",
     "russian": "<b>Э</b>ксрэй",
     "morse":"– · · –"},
         {"name": "Y",
     "value": "Y<b>a</b>nkee",
     "russian": "<b>Я</b>нки",
     "morse":"– · – –"},
         {"name": "Z",
     "value": "Z<b>u</b>lu",
     "russian": "З<b>у</b>–лу",
     "morse":"– – · ·"},
         {"name": "1",
     "value": "One",
     "russian": "Ван",
     "morse": "· – – – –"},
        {"name": "2",
     "value": "Two",
     "russian": "Ту",
     "morse": "· · – – –"},
        {"name": "3",
     "value": "Three",
     "russian": "Три",
     "morse": "· · · – –"},
        {"name": "4",
     "value": "Four",
     "russian": "Ф<b>о</b>ур",
     "morse": "· · · · –"},
        {"name": "5",
     "value": "Five",
     "russian": "Файф",
     "morse": "· · · · ·"},
        {"name": "6",
     "value": "Six",
     "russian": "С<b>и</b>кслу",
     "morse": "– · · · ·"},
        {"name": "7",
     "value": "S<b>e</b>ven",
     "russian": "С<b>е</b>вен",
     "morse": "– – · · ·"},
        {"name": "8",
     "value": "Eight",
     "russian": "Айт",
     "morse": "– – – · ·"},
        {"name": "9",
     "value": "N<b>i</b>ne",
     "russian": "Н<b>а</b>йнер",
     "morse": "– – – – ·"},
        {"name": "0",
     "value": "Z<b>e</b>ro",
     "russian": "З<b>и</b>ро",
     "morse": "– – – – –"},
      {"name": " ",
     "value": "&nbsp;&nbsp;",
     "russian": "&nbsp;&nbsp;",
     "morse": "&nbsp;&nbsp;"},
      {"name": ".",
     "value": "D<b>e</b>cimal",
     "russian": "Д<b>е</b>симал",
     "morse": "· · · · · ·"}

  ]